# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
[\uE0B0](fg:bar_one bg:bar_two)\
$custom$directory\
[\uE0B0](fg:bar_two bg:bar_three)\
$git_branch\
$git_status\
[\uE0B0](fg:bar_three bg:bar_four)\
$c\
$dart\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$lua\
$nodejs\
$nim\
$php\
$python\
$rlang\
$ruby\
$rust\
$scala\
[\uE0B0](fg:bar_four)$all$character"""



right_format = "$cmd_duration"

add_newline = false

palette = 'benn'

# Defines the colour palette for the theme
[palettes.benn]
bar_one = '#DF8601'
bar_two = '#ffa733'
bar_three = '#D1604D'
bar_four = '#32373B'
bar_five = '#222222'
text_one = '#2a2a27'
text_two = '#C0C5C1'
text_three = '#2a2a27'
return_success = '#B6DC76'
return_fail = '#F24236'


[os]
style = 'bg:bar_one fg:text_one'
format = '[ $symbol ]($style)'
disabled = false

[os.symbols]
Alpine = ''
Amazon = ''
Android = ''
Arch = ''
CentOS = ''
Debian = ''
DragonFly = ''
Emscripten = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = '﯑'
Gentoo = ''
HardenedBSD = 'ﲊ'
Illumos = ''
Linux = "\uE712"
Macos = "\uE711"
Manjaro = ''
Mariner = ''
MidnightBSD = ''
Mint = ''
NetBSD = ''
NixOS = ''
OpenBSD = ''
openSUSE = ''
OracleLinux = ''
Pop = ''
Raspbian = ''
Redhat = "\uE7BB"
RedHatEnterprise = "\uE7BB"
Redox = ''
Solus = 'ﴱ'
SUSE = ''
Ubuntu = ''
Unknown = ''
Windows = ''

[directory]
truncation_length = 0
truncation_symbol = '.../'
truncate_to_repo = false
fish_style_pwd_dir_length = 1
style = 'bold fg:text_one bg:bar_two'
format = '[ $path ]($style)'

[custom.home]
when = ''' test "$HOME" = "$PWD" '''
style = 'bold fg:text_one bg:bar_two'
symbol = ' '

[custom.folder]
when = ''' test "$HOME" != "$PWD" '''
style = 'bold fg:text_one bg:bar_two'
symbol = ' '

[directory.substitutions]
'Documents' = ' '
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '

[git_branch]
symbol = ' '
style = 'fg:text_three bg:bar_three'
format = '[ $symbol $branch ]($style)'

[git_status]
style = 'fg:text_three bg:bar_three'
format = '[$all_status$ahead_behind ]($style)'

[c]
symbol = ' '
style = 'fg:text_two bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[dart]
symbol = ' '
style = 'fg:text_two bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = ' '
style = 'fg:text_two bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = ' '
style = 'fg:text_two bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ' '
style = 'fg:text_two bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = ' '
style = 'fg:text_two bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ' '
style = 'fg:text_two bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = ' '
style = 'fg:text_two bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = ' '
style = 'fg:text_two bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ' '
style = 'fg:text_two bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = ' '
style = 'fg:text_two bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[php]
symbol = ' '
style = 'fg:text_two bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ' '
style = 'fg:text_two bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[rlang]
symbol = 'ﳒ '
style = 'fg:text_two bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[ruby]
symbol = ' '
style = 'fg:text_two bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ''
style = 'fg:text_two bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = ' '
style = 'fg:text_two bg:bar_four'
format = '[ $symbol ($version) ]($style)'

[time]
disabled = true
time_format = '%R' # Hour:Minute Format
style = 'fg:text_three bg:bar_three'
format = '[   $time ]($style)'

[cmd_duration]
disabled = false
min_time = 100
show_milliseconds = true
style = 'fg:text_three bg:bar_three'
format = "[\uE0B2](fg:bar_three)[   $duration ]($style)"

[character]
success_symbol = "[❯](return_success)"
error_symbol = "[❯](return_fail)"

[kubernetes]
disabled = false
style = 'fg:text_two'
format = '[ ☸ $context \($namespace\) ]($style)'
detect_folders = [".kubefiles", "kubefiles", "helmfiles"]